### ISSUE TITLE
"hidden" scroll bar that you need to reveal by panning in order to scroll the view.

### ISSUE THREAD

**Issue by mstahv** [vaadin/multiplatform-runtime#59] opened 2019-11-25 13:22 UTC
Feedback from a customer: with their app there is "hidden" scroll bar that you need to reveal by panning in order to scroll the view. This does not happen with Vaadin 7 native, only with MPR.

Screenshots and more details in prodpad: https://app.prodpad.com/feedback/418522/canvas

**Comment by mehdi-vaadin** [comment] 2019-11-25 13:56
It might be a duplicate of #58.

**Comment by mehdi-vaadin** [comment] 2019-11-29 13:20
I'm closing this in favor of #58

**Closed by mehdi-vaadin** 2019-11-29 13:20 UTC
