### ISSUE TITLE
Legacy components are not attached to view after adding font-awesome-iron-iconset add-on

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/multiplatform-runtime#120] opened 2023-02-06 14:31 UTC
In V14 application using MPR, legacy components are not attached to view after adding the [font-awesome-iron-iconset](https://vaadin.com/directory/component/fontawesome-iron-iconset) add-on dependency. [Here](https://github.com/onuridrisoglu/mpr-demo) is a very simple reproducible example. 

I tried both with `mpr-v8` and `mpr-v7`, and the same problem exists in both versions.
If you run the application in production mode, or build the frontend even in development mode, it works fine. 

- Versions:
    - Vaadin Framework: 14.8.20
    - Flow: 2.7.6
    - MPR: 2.2.10
    - Java JRE / JDK : 1.8
    - Operating System: Mac OS
    - Browser (if applicable): Chrome Version 109.0.5414.119

**Comment by mshabarov** [comment] 2023-02-07 11:26
A quick note (maybe not relevant to the issue): Flow 2.8 corresponds to Vaadin 14.9, but you use 14.8. Can you please try with 14.9?

**Comment by onuridrisoglu** [comment] 2023-02-08 08:27
You're right, I changed it `2.7.6` and also updated it in the demo project. But the issue still remains

**Comment by mshabarov** [comment] 2023-03-14 07:34
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by caalador** [comment] 2023-04-06 10:06
The issue is the `         <g id="vaadin">` in `fab.js` which overrides the window.vaadin scope in the browser where the Framework bootsrap `/framework/VAADIN/vaadinBootstrap.js`  sets the initApplication function [`window.vaadin = window.vaadin || { initApplication: function(appId, config) .... `]
This doesn't work as `window.vaadin` returns the `<g id="vaadin">` item and the framework intialization is never done as the initApplication is never added to the page.
To fix this the `font-awesome-iron-iconset` should rename the VAADIN icon to `VAADIN_ICON` in `FontAwesome.java` and `vaadin-icon` in `fab.js`

**Comment by javier-godoy** [comment] 2023-04-06 13:59
@caalador Thanks for the detailed analysis. I've created an issue for renaming the VAADIN icon in font-awesome-iron-iconset.

**Comment by mcollovati** [comment] 2023-04-17 07:31
@onuridrisoglu can we close this issue, as it seems, the problem has been fixed in `font-awesome-iron-iconset`?

**Comment by javier-godoy** [comment] 2023-04-17 16:01
Issue has been fixed in version [3.1.0](https://github.com/FlowingCode/FontAwesomeIronIconset/releases/tag/font-awesome-iron-iconset-3.1.0) of font-awesome-iron-iconset. As suggested by @caalador the icon has been renamed as `vaadin-icon`. For compatibility, `FontAwesome.Brands.VAADIN` also resolves to "vaadin-icon" (thus it does not contribute a `<g id="vaadin">` element).
![image](https://user-images.githubusercontent.com/11554739/232542733-85df4e76-e428-4d7b-ad65-1101f5a25e1e.png)

**Closed as completed** 2023-04-18 09:31 UTC
Labels: bug, BFP, waiting for author, Impact: Low, Severity: Major
