### ISSUE TITLE
"This UI instance is already initialized" appearing in production 

### ISSUE THREAD

**Issue by TatuLund** [vaadin/multiplatform-runtime#54] opened 2019-10-01 05:34 UTC
We have observed this error happening sometimes in production environment

```
java.lang.IllegalStateException: This UI instance is already initialized (as UI id 0) and can therefore not be initialized again (as UI id 1). Please make sure you are not accidentally reusing an old UI instance.

                      at com.vaadin.ui.UI.doInit(UI.java:682)

                      at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:222)

                      at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)

                      at com.vaadin.mpr.core.MprUIInitHandler.synchronizedHandleRequest(MprUIInitHandler.java:73)

                      at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)

                      at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)

                      at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)

                      at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)


```

**Comment by Legioth** [comment] 2019-10-03 19:13
My best guess of what's happening here is that two separate tabs are opened simultaneously, each having their own MPR contents. For each of those, there's logic that sees that the next legacy UI id for the session is 0, which is sent to the client-side counterpart for each tab. After this, each tab goes on to send an UI init request with `ui=0` as a parameter. This succeeds for the first one to be processed, but fails for the second once since `getNextUIid()` now returns 1 instead of the expected 0.

If this is the case, then one way of fixing this would be that the bootstrapping logic uses its own counter for assigning a unique id to each legacy UI. Furthermore, `getNextUIid()` needs to be overridden so that the logic picks the corresponding ID from the current request instead of using the counter.

**Comment by mehdi-vaadin** [comment] 2019-10-11 12:56
@TatuLund did Leif guess correctly? Does the exception happen when you open multiple tabs?

**Comment by TatuLund** [comment] 2019-10-11 12:59
@mehdi-vaadin no, we have observed it also in single browser tab scenario. I have created also another ticket #56, which is earlier observation. Once we made workaround for that, this issue (#54) emerged. We are trying now to investigate possible role of Vaadin 7 add-on (PopupExtension) in this case.

**Comment by mehdi-vaadin** [comment] 2019-10-11 13:21
@TatuLund please inform us about the conclusion of the investigation on the add-on.

**Comment by TatuLund** [comment] 2019-10-16 05:03
@mehdi-vaadin Removal of the add-on did not help.

We have some additional data that indicates that the test users in US had more occurrences of this issue than users in Finland. The server is in Finland, so that gives indication that added latency could make this more likely.

**Comment by Legioth** [comment] 2019-10-16 17:18
I had misunderstood the purpose of the `ui` parameter in the request. That parameter defines the id of the Flow UI from which the newly created MPR UI should find its contents - it has nothing to do with the id of the MPR UI. This means that we're back at square one when it comes to guesses about the cause of this problem.

It still seems like `doInit` is run multiple times for the same UI instance since that's the only method that writes to the `uiId` parameter. The only obviously findable code path to `doInit` goes through `getBrowserDetailsUI`. That method calls `AbstractMprUIProvider.createInstance(UICreateEvent)` which tries to use an existing instance in the session based on the Flow UI id and otherwise creates a new instance. This means that running `getBrowserDetailsUI` twice with the same `ui` request parameter (i.e. for the same Flow UI) will lead to the original stacktrace.

`getBrowserDetailsUI` is (supposedly) only triggered by "browser details" requests, i.e. requests with a `v-browserDetails` request parameter. Requests with this parameter are only sent through `fetchRootConfig` in `vaadinBootstrap.js`, which is (assumingly) only triggered through `executeJavaScript` from `AbstractLegacyWrapper.initContent(UI)`. This method in turn is only called if there isn't already a `ComponentUtil.getData(ui, AbstractMprUIContent.class)`. The corresponding `setData` call is done by `initContent`. This is also the origin of the `id` parameter, which is passed as part of a larger JSON structure through the `executeJavaScript` invocation.

There is a window of opportunity for `initContent` to be run multiple times for the same UI instance if `getData` is checked again before `setData` has been run. This may happen from a background thread if that thread doesn't properly lock the session or reentrantly if anything happening in between may cause another `LegacyWrapper` instance to be attached. I cannot find any obvious reason for a reentrant invocation, the only non-trivial methods called between `getData` and `setData` are `getWidgetset()` and `createMprUIContent()`, which both seem safe. Modification from another thread is prevented by `checkHasLock()` in the beginning of `initContent` which means that this condition should be caught with enabled assertions in production mode and irregardless of the assertion setting when production mode is disabled.

Some potential scenarios that I cannot rule out:
*  The "same" `v-browserDetails` request is resent e.g. because of a network error. There is no explicit logic for resending and the browser is not supposed to resend it on its own since its a POST and should thus not be assumed to be idempotent.
* The single `executeJavaScript` invocation causes the same script to be evaluated twice.
* There is some case where any of the key methods in my assumed chain of events can be called in some other way than what I have discovered, e.g. using reflection or through application code.
* There is a stray `v-browserDetails` request that originates from an old session that has since been closed and a new session containing a UI with the same id has been created before the request reaches the server.

**Comment by johannest** [comment] 2019-10-21 08:36
Happened to me now locally after page refresh of V13 view in the same MPR application as Tatu uses
Win 10 Pro
Chrome
Vaadin 7.7.17
Platform 13.0.13
Mpr-v7 2.0.0

**Comment by caalador** [comment] 2019-10-21 09:38
Could you do a build of branch issues/54_lock-for-getContent and test if the exception still happens, as I don't have a project that I could replicate the exception with.

**Comment by Legioth** [comment] 2019-10-21 09:57
@caalador So your hypothesis is that someone is calling `getContent` without already having the UI instance locked? Wouldn't it in that case be more appropriate to test that the UI session is locked by the current thread?

**Comment by johannest** [comment] 2019-10-21 10:31
We will try that one

**Comment by johannest** [comment] 2019-10-23 10:38
@caalador @Legioth The fix didn't help, the issue is still there

**Comment by johannest** [comment] 2019-10-23 11:50
If we can catch this with debugger, what information would help you/us to best find out the root cause?

**Comment by TatuLund** [comment] 2019-10-31 12:14
We have observed client side exception happening on Vaadin 7 widgetset at the same time the error happens (unfortunatelly widgetset was obfuscated)

Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.communication.Heartbeat
INFO: Setting hearbeat interval to -1sec.
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.VConsole
INFO: New window width: 1532
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.VConsole
INFO: New window height: 915
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.VConsole
INFO: New parent width: 1532
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.VConsole
INFO: Running layout functions due to window or parent resize
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.communication.ServerRpcQueue
WARNING: Trying to invoke method on not yet started or stopped application
vBb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513
gCb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4115
fCb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3172
lCb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:1995
nif @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:851
$sc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3983
Ysc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3513
BMc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3387
yqe @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4520
qy @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4512
Ky @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4256
By @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3914
TIb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:1458
bJb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513
ry @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2423
t1d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3149
u1d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4439
M1d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4519
Hb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4511
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2245
Li @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2051
Oi @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3869
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3559
setTimeout (async)
Jb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2048
Bb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3375
B1d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4519
UIb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4004
z1d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4519
ZIb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3577
rJb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2753
KJb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:1772
Bpe @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4404
gdc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4442
Fcc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4514
pj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3839
hj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3115
tj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4511
nj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:798
Li @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2051
Oi @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3869
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3559
d @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3457
setTimeout (async)
qj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3458
jj @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3227
Llc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2739
Dcc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:1898
Li @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2051
Oi @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3869
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3559
registerWidgetset @ vaadinBootstrap.js:286
Bcc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2680
tcc @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4450
qBb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2780
g @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3823
Li @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:2051
Oi @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3869
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3559
mBb @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:3824
eval @ com.myapp.ui.desktop.DesktopWidgetSet-0.js:4522
(anonymous) @ VM12754:1
m @ com.myapp.ui.desktop.DesktopWidgetSet.nocache.js?1572523315186:9
(anonymous) @ com.myapp.ui.desktop.DesktopWidgetSet.nocache.js?1572523315186:10
l @ com.myapp.ui.desktop.DesktopWidgetSet.nocache.js?1572523315186:6
A.com_kemira_ep_frontend_ui_desktop_DesktopWidgetSet.onScriptDownloaded @ com.myapp.ui.desktop.DesktopWidgetSet.nocache.js?1572523315186:10
(anonymous) @ EEE659B2A4DAA08B5EEE145B18C757F5.cache.js:1
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: Starting layout phase
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: Measured 6 non connector elements
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: Pass 1 measured 2 elements, fired 0 listeners and did 1 layouts.
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: Pass 2 measured 1 elements, fired 0 listeners and did 0 layouts.
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: No more changes in pass 3
com.myapp.ui.desktop.DesktopWidgetSet-0.js:4513 Thu Oct 31 14:01:56 GMT+200 2019 com.vaadin.client.LayoutManager
INFO: Total layout phase time: 11ms
client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:188 JSON parsing took 0.485ms

**Comment by TatuLund** [comment] 2019-11-05 08:49
According the experimentation we have done this issue seems to happen only when closeIdleSession=true.

**Comment by denis-anisimov** [comment] 2019-11-06 13:17
Could you please try this branch  https://github.com/vaadin/multiplatform-runtime-internal/tree/54-avoid-reinit-fw-ui and let me know whether the issue is reproducible with it ?

**Comment by TatuLund** [comment] 2019-11-06 14:43
I made new snapshot build for testing this. I let you know how it works.

**Comment by denis-anisimov** [comment] 2019-11-06 14:44
Thank you.

**Comment by joheriks** [comment] 2019-11-12 13:31
Closed by https://github.com/vaadin/multiplatform-runtime-internal/pull/342

**Closed by joheriks** 2019-11-12 13:31 UTC
Labels: BFP, bug
