### ISSUE TITLE
Docs in Step 3 contain an invalid link

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/multiplatform-runtime#34] opened 2018-12-10 08:52 UTC
https://vaadin.com/docs/v12/mpr/introduction/step-3-cdi.html

Sub chapter _What to do with CDIView_ contains the link _Migrating Views to Flow Routes_. Leads to a 404.

**Comment by caalador** [comment] 2018-12-21 07:09
duplicate of https://github.com/vaadin/multiplatform-runtime-internal/issues/279

**Closed by caalador** 2018-12-21 07:09 UTC
Labels: Tutorial, bug, duplicate
